"""make background_tasks.project_id nullable

Revision ID: 86ea8f0adfbf
Revises: abc12345
Create Date: 2026-05-06 22:03:45.189645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86ea8f0adfbf'
down_revision: Union[str, None] = 'abc12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('background_tasks', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               comment='项目ID(灵感任务创建前为空)',
               existing_comment='项目ID')
    op.alter_column('background_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               comment='任务类型: outline_new/outline_continue/outline_expand/chapter_generate/chapter_batch/wizard',
               existing_comment='任务类型',
               existing_nullable=False)
    op.alter_column('background_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态: pending/running/completed/failed/cancelled',
               existing_comment='任务状态',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='进度百分比(0-100)',
               existing_comment='进度百分比',
               existing_nullable=True)
    op.alter_column('background_tasks', 'task_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务输入参数(JSON)',
               existing_comment='任务输入参数',
               existing_nullable=True)
    op.alter_column('background_tasks', 'task_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务结果(JSON)',
               existing_comment='任务结果',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='进度详情: {stage, message, word_count, etc.}',
               existing_comment='进度详情',
               existing_nullable=True)
    op.drop_index('ix_background_tasks_user_project', table_name='background_tasks')
    op.alter_column('projects', 'cover_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='封面状态: none/generating/ready/failed',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'cover_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'none'::character varying"),
               existing_comment='封面状态: none/generating/ready/failed',
               existing_nullable=False)
    op.create_index('ix_background_tasks_user_project', 'background_tasks', ['user_id', 'project_id', 'status'], unique=False)
    op.alter_column('background_tasks', 'progress_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='进度详情',
               existing_comment='进度详情: {stage, message, word_count, etc.}',
               existing_nullable=True)
    op.alter_column('background_tasks', 'task_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务结果',
               existing_comment='任务结果(JSON)',
               existing_nullable=True)
    op.alter_column('background_tasks', 'task_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务输入参数',
               existing_comment='任务输入参数(JSON)',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='进度百分比',
               existing_comment='进度百分比(0-100)',
               existing_nullable=True)
    op.alter_column('background_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_comment='任务状态: pending/running/completed/failed/cancelled',
               existing_nullable=True)
    op.alter_column('background_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               comment='任务类型',
               existing_comment='任务类型: outline_new/outline_continue/outline_expand/chapter_generate/chapter_batch/wizard',
               existing_nullable=False)
    op.alter_column('background_tasks', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               comment='项目ID',
               existing_comment='项目ID(灵感任务创建前为空)')
    # ### end Alembic commands ###